---
- hosts: sql-server
  serial: 1
  tasks:
  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    become: yes
  - name: Add MSSQL repos
    apt_repository:
      repo: deb {{ item }}  bionic main
      state: present
    with_items:
      - https://packages.microsoft.com/ubuntu/18.04/prod
      - https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019
    become: yes
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    become: yes
    changed_when: false
  - name: "Upgrade all packages to the latest version"
    apt:
      name: "*"
      state: latest
    become: yes
  - name: Install mssql, sqlcmd and odbc driver 
    apt:
      name: 
        - mssql-tools
        - unixodbc-dev
        - mssql-server
      state: present
    environment:
      ACCEPT_EULA: 'Y'
    become: yes
  - name: Stop service mssql-server, if started
    service:
      name: mssql-server
      state: stopped
    become: yes
  - name: Configure MSSQL & set password
    command: /opt/mssql/bin/mssql-conf -n setup
    environment:
      MSSQL_PID: 'Developer'
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "{{ sqlserver_sa_password }}"
    become: yes